### ISSUE TITLE
[Question] Any play to open souce onnx-caffe converter?

### ISSUE THREAD

**Issue by zhiqwang** [NetEase-GameAI/ResNeSt-caffe#2]
Hi! Thx for your sharing.
This caffe version of ResNeSt is very convenient for deploying it to other platform. I want to know whether there is any chance to open source the onnx2caffe converter?

**Comment by NetEase-GameAI** [comment]
For now, it's just an internal experimental tool, and we only test it on ~10 models. So it won't be avaliable until being more robust and powerful.

**Comment by zhiqwang** [comment]
Thanks for your reply.
